"""Model card: one auditable report for a model version, generated from the files that version saved.

Every number comes from models/v{N}/ (metrics.json, manifest.json, features.json, and the point-in-time
audit and backtest results when they exist). Nothing is typed by hand, so the card cannot drift from the
model. Numbers a version did not compute are marked as pending rather than left out. The structure follows
the items TRIPOD+AI asks a prediction-model report to state: outcome, population, predictors and when they
were measured, sample sizes, missing data, model building, validation, performance, and limitations.
"""
import json
from pathlib import Path

from ctrisk.ml.features import CATEGORICAL, EDIT_PRONE, FAERS

PENDING = "pending (next `make train`)"
COHORT_LAST_ARCHIVE = "2020-12-01"     # the audit covers 2017-2020 starts; earlier last archives leave it partial
POINT_IN_TIME = set(FAERS) | {"sponsor_prior_trials", "sponsor_prior_termination_rate", "sponsor_trials_started_2y"}
ABLATION_TEXT = {
    "lightgbm_no_text": "without registration text",
    "lightgbm_no_burden": "without burden & eligibility fields",
    "lightgbm_no_faers": "without FAERS reporting history",
    "lightgbm_stable_only": "without any edit-prone field or text (floor under post-start edits)",
}


def _f(v, d=3) -> str:
    return PENDING if v is None else f"{v:.{d}f}"


def _pct(v, d=1) -> str:
    return PENDING if v is None else f"{v * 100:.{d}f}%"


def _events(split: dict) -> str:
    return f"{round(split['n'] * split['base_rate']):,} ({_pct(split['base_rate'])})"


def _timing(column: str) -> str:
    if column in POINT_IN_TIME:
        return "as of the start date"
    if column in EDIT_PRONE:
        return "latest record; often edited after start"
    return "latest record"


def _table(header: list[str], rows: list[list]) -> list[str]:
    return ["| " + " | ".join(header) + " |", "|" + "---|" * len(header),
            *["| " + " | ".join(str(c) for c in r) + " |" for r in rows], ""]


def _fit(test: dict) -> str:
    fit = test.get("calibration_fit")
    return PENDING if not fit else f"intercept {fit['intercept']:.2f} (0 is ideal), slope {fit['slope']:.2f} (1 is ideal)"


def _status(audit: dict | None) -> str:
    """Preliminary until a complete point-in-time audit exists; then what it measured."""
    latest = ("Registry features come from the latest version of each ClinicalTrials.gov record, not the version "
              "at the trial's start.")
    archives = (audit or {}).get("archives") or []
    if audit and archives and archives[-1] >= COHORT_LAST_ARCHIVE:
        m = audit["matched"]
        lo, hi = m["auc_drop_ci95"]
        return (f"**Audited on 2017–2020 starts.** {latest} Scoring the same trials with registry fields as they "
                f"stood at each start instead changes AUC by {-m['auc_drop']:+.3f} (95% CI {-hi:+.3f} to {-lo:+.3f}) "
                f"on {m['n']:,} trials (point-in-time audit below). The 2008–2016 training and test years predate "
                "the archives and could not be audited directly.")
    return (f"**Preliminary.** {latest} The held-out numbers below may be inflated by edits made after trials "
            "started. " + ("The point-in-time audit below covers only part of 2017–2020." if audit else
                           "The point-in-time audit (`make audit-build audit`) has not been run for this version."))


def card(metrics: dict, manifest: dict, features: dict, audit: dict | None = None, backtest: dict | None = None) -> str:
    t = metrics["targets"]["label"]
    lg, base = t["models"]["lightgbm"], t["models"]["logistic_regression"]
    test, sp = lg["test"], t["splits"]
    v = f"v{manifest['version']}"
    out = [f"# Model card: trial termination risk, {v}", "",
           (f"Generated by `make report` from `models/{v}/`. Trained {manifest['trained_at'][:10]} at git "
           f"`{manifest['git']}` on the Snowflake snapshot `{manifest['snowflake_clone']}`."), "",
           "## Status", "",
           _status(audit) + " AUC measures ranking. Risk percentages are calibrated on 2015–2016 starts only. "
           "Per-trial contributors describe the model, not causes of termination.", "",
           "## What it predicts", "",
           "- **Outcome:** a registered trial ends as `TERMINATED` (1) rather than `COMPLETED` (0).",
           ("- **Population:** interventional Phase 1–3 drug or biologic trials on ClinicalTrials.gov (AACT). "
           "Withdrawn, suspended, unknown-status and still-running trials carry no label and are excluded from "
           "training and evaluation."),
           "- **Scored:** trials currently not yet recruiting, recruiting, active, or enrolling by invitation.",
           ("- **Intended use:** ranking active trials for review. Not intended as a probability for an individual "
           "trial's decision-making, and not a causal account of why trials stop."), "",
           "## Predictors and when they were measured", ""]
    cols = features["columns"]
    out += _table(["Predictor", "Type", "Measured"],
                  [[f"`{c}`", "categorical" if c in CATEGORICAL else "numeric / flag", _timing(c)] for c in cols]
                  + [["registration text", f"TF-IDF 1–2grams → SVD, {features.get('text_components', 0)} components",
                      "latest record; often edited after start"]])
    if features.get("excluded"):
        out += [("Left out because the point-in-time audit found them edited after start: "
                 + ", ".join(f"`{c}`" for c in features["excluded"])
                 + " (`docs/audits/2026-10-01-point-in-time.md`)."), ""]
    out += [(f"{sum(c in POINT_IN_TIME for c in cols)} of {len(cols)} tabular predictors are measured as of the "
            "start date (FAERS reports received before the start month; sponsor trials that ended or started "
            "before the start date). The rest come from the latest registry record. Missing values: LightGBM's "
            "native handling; median imputation plus missing indicators for the logistic baseline; unseen "
            "categories at scoring map to missing."), "",
            "## Samples", ""]
    out += _table(["Split", "Start years", "Trials", "Terminated", "Role"], [
        ["train", "2008–2014", f"{sp['train']['n']:,}", _events(sp["train"]),
         "fit; hyperparameters tuned on <2013 vs 2013–2014"],
        ["test", "2015–2016", f"{sp['test']['n']:,}", _events(sp["test"]),
         "headline metrics; never used for tuning or text fitting"],
        ["recent", "2017–2020", f"{sp['recent']['n']:,}", _events(sp["recent"]),
         "secondary; still censored, over-represents early terminations"]])
    grid = t.get("grid", [])
    params = t["params"]
    out += ["Event counts are n × base rate from the saved metrics, rounded."
            if "positives" not in test else f"Test terminations counted directly: {test['positives']:,}.", "",
            "## Model", "",
            (f"LightGBM, {params['n_estimators']} trees, {params['num_leaves']} leaves, learning rate "
            f"{params['learning_rate']}, min {params['min_child_samples']} trials per leaf; chosen from a "
            f"{len(grid)}-point grid by AUC on the inner 2013–2014 split with early stopping."
            + (f" The scored model is an ensemble of {manifest['seeds']} such fits that differ only in the random "
               "seed behind row and column subsampling, with their log-odds averaged (see stability below)."
               if manifest.get("seeds", 1) > 1 else "")
            + " Baseline: logistic regression on the same tabular inputs without text."), "",
            "## Performance on 2015–2016 starts (held out)", ""]
    ci = test.get("roc_auc_ci95") or [None, None]
    out += _table(["Metric", "LightGBM", "Logistic baseline"], [
        ["ROC AUC (95% bootstrap CI)", f"{test['roc_auc']:.3f} ({_f(ci[0])}–{_f(ci[1])})", f"{base['test']['roc_auc']:.3f}"],
        ["PR AUC", f"{test['pr_auc']:.3f}", f"{base['test']['pr_auc']:.3f}"],
        ["Termination rate in the riskiest tenth", _pct(test["precision_top_10pct"]), _pct(base["test"]["precision_top_10pct"])],
        ["Base rate", _pct(test["base_rate"]), ""],
        ["Brier score", f"{test['brier']:.4f}", f"{base['test']['brier']:.4f}"],
        ["Calibration", _fit(test), ""]])
    if test.get("calibration"):
        out += ["Calibration by tenth of predicted risk:", ""]
        out += _table(["Tenth", "Mean predicted", "Observed", "Trials"],
                      [[r["bin"] + 1, _pct(r["mean_predicted"]), _pct(r["observed"]), f"{r['n']:,}"]
                       for r in test["calibration"]])
    out += ["## Robustness", "", "Test AUC when the model is retrained without a feature group:", ""]
    out += _table(["Model", "Test AUC", "Change"],
                  [["full model", f"{test['roc_auc']:.3f}", ""]]
                  + [[ABLATION_TEXT[k], f"{t['models'][k]['test']['roc_auc']:.3f}",
                      f"{t['models'][k]['test']['roc_auc'] - test['roc_auc']:+.3f}"] if k in t["models"]
                     else [ABLATION_TEXT[k], PENDING, ""] for k in ABLATION_TEXT])
    folds = t.get("rolling_origin")
    out += [("Rolling origin: fit on training starts before each window, test on the two-year window. "
            "Parameters were tuned on 2013–2014, so the earlier windows are slightly optimistic."), ""]
    out += (_table(["Test starts", "Trained on", "Trials", "Terminated", "AUC", "Calibration"],
                   [[f["test_years"], f"{f['train_n']:,}", f"{f['n']:,}", f"{f['positives']:,}", f"{f['roc_auc']:.3f}",
                     _fit(f)] for f in folds]) if folds else [PENDING, ""])
    out += [f"Recent starts (2017–2020, censored): AUC {lg['recent']['roc_auc']:.3f} on {lg['recent']['n']:,} trials.", ""]
    for key, title in (("by_sponsor_class", "sponsor class"), ("by_phase", "phase"), ("by_start_year", "start year")):
        groups = t.get(key)
        out += [f"Test AUC by {title}:", ""]
        out += (_table(["Group", "Trials", "Terminated", "AUC"],
                       [[g, f"{r['n']:,}", f"{r['positives']:,}" if "positives" in r else "", f"{r['roc_auc']:.3f}"]
                        for g, r in groups.items()]) if groups else [PENDING, ""])
    stab = t.get("refit_stability")
    if stab:
        out += ["## Stability across refits", "",
                (f"The model was refit independently (other seeds, training rows shuffled, text refit) and both fits "
                 f"scored the same {stab['trials']:,} trials (test and active). Percentiles are among active trials, "
                 "as the lookup shows them."), ""]
        out += _stability_table(stab)
        out += [("The text components are computed exactly (ARPACK), so they do not depend on row order; the "
                 "randomized solver used before v6 changed half of them with the order of the training rows."), ""]
    out += ["## Point-in-time audit (2017–2020 starts)", ""]
    if audit:
        m, s = audit["matched"], audit["strict"]
        archives = audit.get("archives") or []
        line = f"{audit['n_matched']:,} of {audit['n_cohort']:,} trials had an archived record"
        if archives:
            line += f", drawn from {len(archives)} AACT archives dated {archives[0]} to {archives[-1]}"
        out += [line + ".", ""]
        if archives and archives[-1] < COHORT_LAST_ARCHIVE:
            out += [(f"**Partial: archives cover only part of 2017–2020.** Trials that started after {archives[-1]} "
                     "are matched to an older record or not at all; the decision waits for the full set."), ""]
        areas = audit.get("areas_from_latest") or {}
        if areas:
            share = max(areas.values())
            out += [("Archives without MeSH ancestors cannot say a trial's top-level disease area; "
                     f"disease areas kept from the latest record for {_pct(share)} of trials."), ""]
        out += _table(["Trials", "n", "Latest-record AUC", "Point-in-time AUC", "Drop (95% CI)"],
                      [[name, f"{r['n']:,}", f"{r['latest']['roc_auc']:.3f}", f"{r['point_in_time']['roc_auc']:.3f}",
                        f"{r['auc_drop']:+.3f} ({r['auc_drop_ci95'][0]:+.3f} to {r['auc_drop_ci95'][1]:+.3f})"]
                       for name, r in (("with an archived record", m), ("record predates start", s))])
        top = list(audit["change_rates"].items())[:8]
        out += ["Fields whose values changed most unevenly between start and now (terminated minus completed):", ""]
        out += _table(["Field", "Changed, terminated", "Changed, completed", "AUC drop if only this is point-in-time"],
                      [[f"`{c}`", _pct(r["terminated"]), _pct(r["completed"]),
                        f"{audit['swap_one_column'].get(c, 0):+.3f}"] for c, r in top])
        if audit.get("unseen_levels"):
            out += [f"Archived categories the model never saw (format drift, or a record edited from outside the modelled population, e.g. phase N/A to Phase 2): {audit['unseen_levels']}", ""]
    else:
        out += ["Not run for this version. See `docs/plans/2026-09-29-m6-honest-model.md`, Task 7.", ""]
    out += ["## Prospective backtest", ""]
    runs = (backtest or {}).get("by_version", {})
    scored = {k: r for k, r in runs.items() if "roc_auc" in r}
    if scored:
        out += [f"Run {backtest['run_at'][:10]}: scores written by each version, against outcomes known then.", ""]
        out += _table(["Version", "First scored", "Resolved trials", "Terminated", "AUC (95% CI)", "Calibration"],
                      [[k, r["first_scored"], f"{r['n']:,}", f"{r['positives']:,}",
                        f"{r['roc_auc']:.3f} ({r['roc_auc_ci95'][0]:.3f}–{r['roc_auc_ci95'][1]:.3f})", _fit(r)]
                       for k, r in scored.items()])
        out += ["Resolved trials over-represent early terminations until most scored trials have finished.", ""]
    else:
        out += [("No scored trial has resolved with both outcomes yet. `make backtest` compares scores written "
                 "earlier with outcomes known now; re-run yearly."), ""]
    out += ["## Other targets", ""]
    rows = []
    for key in ("label_enrollment", "label_safety"):
        o = metrics["targets"].get(key)
        if o:
            ot = o["models"]["lightgbm"]["test"]
            oci = ot.get("roc_auc_ci95") or [None, None]
            rows.append([o["description"], f"{o['splits']['test']['n']:,}", _events(o["splits"]["test"]),
                         f"{ot['roc_auc']:.3f} ({_f(oci[0])}–{_f(oci[1])})",
                         f"{o['models']['logistic_regression']['test']['roc_auc']:.3f}"])
    out += _table(["Target", "Test trials", "Positives", "AUC (95% CI)", "Baseline"], rows)
    out += [("Reason-specific targets compare trials terminated for that reason with completed trials; trials "
            "terminated for other reasons are left out. Reasons come from free text (safety labels ≈70–80% precise)."), "",
            "## Limitations", "",
            "- Registry features describe the latest record, not the record at start (see Status).",
            "- Planned enrollment and site counts are excluded because the current record reflects the outcome.",
            ("- FAERS features are a historical reporting signal: FAERS has duplicate and incomplete reports and "
            "cannot establish causation or incidence. From v5 they use every quarter 2004–2026; earlier versions "
            "used the first quarter of each year."),
            ("- The test period is one two-year window of one registry; performance on other periods or registries "
            "is untested except for the rolling-origin windows above."),
            "- Contributors are SHAP values of this model: associations, not mechanisms.", ""]
    return "\n".join(out)


def _latest_backtest(models_dir: Path) -> dict | None:
    runs = sorted(models_dir.glob("backtest_*.json"))
    return json.loads(runs[-1].read_text()) if runs else None


COHORT_NAMES = {"test": "2015–2016 starts", "recent": "2017–2020 starts"}


def _stability_table(stab: dict) -> list[str]:
    """One fit vs the seed ensemble: how far two independent refits disagree on the same trials."""
    one, ens = stab["single_fit"], stab["ensemble"]
    return _table(["", "One fit", f"Ensemble of {stab['seeds']}"],
                  [["Rank correlation between the two fits", f"{one['spearman']:.3f}", f"{ens['spearman']:.3f}"],
                   ["Median change in a trial's score", _pct(one["median_abs_change"]), _pct(ens["median_abs_change"])],
                   ["95th percentile change in score", _pct(one["p95_abs_change"]), _pct(ens["p95_abs_change"])],
                   ["Median change in percentile", f"{one['median_percentile_change']:.1f} points",
                    f"{ens['median_percentile_change']:.1f} points"],
                   ["Trials moving more than 5 percentile points", _pct(one["share_moved_over_5_points"]),
                    _pct(ens["share_moved_over_5_points"])],
                   ["Trials moving more than 10 percentile points", _pct(one["share_moved_over_10_points"]),
                    _pct(ens["share_moved_over_10_points"])]])


def _recalibration(r: dict) -> list[str]:
    """The survival card's section on recalibrating to recent calendar time, and its landmark backtest."""
    a1, b1, a2, b2 = r["serving"]["params"]
    out = ["## Recalibration to today's risk", "",
           ("Trials that started 2015 or later (none used to fit the hazards), by the calendar year of each 6-month "
            "period they were at risk in, as learned:"), ""]
    out += _table(["Calendar year", "Periods at risk", "Terminated, observed / expected", "Completed, observed / expected"],
                  [[x["year"], f"{x['periods_at_risk']:,}", f"{x['terminated_observed_over_expected']:.2f}",
                    f"{x['completed_observed_over_expected']:.2f}"] for x in r["by_calendar_year"] if x["year"] >= 2016])
    out += [("Terminations have run above expectation since 2016, and further above it since 2020. In the most recent "
             "calendar years completions fall short as well: that is reporting lag (sponsors record that a trial ended "
             f"months later), not lower risk, so the last {r['lag_years']:g} years before the snapshot are left out."), "",
            (f"The per-period log-odds of terminating (vs still running) are mapped through an intercept and a slope, "
             f"and the same for completing, fit by maximum likelihood on the {r['window_years']:g} calendar years "
             f"{r['serving']['fit_window'][0]} to {r['serving']['fit_window'][1]} ({r['serving']['fit_periods']:,} "
             f"person-periods). Served: terminating {a1:+.2f} + {b1:.2f} × learned log-odds; completing {a2:+.2f} + "
             f"{b2:.2f} × learned log-odds. A slope below 1 means the learned termination risks were too spread out."), "",
            ("**Backtest, as the lookup uses it.** At each landmark date, the trials then running (at most 6 years in) get "
             f"their probability of termination in the next {r['horizon_years']:g} years, recalibrated only on calendar "
             f"time ending {r['lag_years']:g} years before the landmark, and are compared with what happened to them:"), ""]
    out += _table(["Landmark", "Running trials", "Observed", "Predicted, as learned", "Predicted, recalibrated",
                   "Time-AUC", "Yes/no model time-AUC"],
                  [[b["landmark"], f"{b['running']:,}", _pct(b["observed"]), _pct(b["predicted_as_learned"]),
                    _pct(b["predicted_recalibrated"]), f"{b['time_auc']:.3f}",
                    f"{b['time_auc_yes_no_model']:.3f}" if "time_auc_yes_no_model" in b else "–"] for b in r["backtest"]])
    last = r["backtest"][-1]
    out += [f"By decile of predicted risk, trials running at {last['landmark']}:", ""]
    out += _table(["Decile", "As learned", "Recalibrated", "Observed"],
                  [[c["bin"] + 1, _pct(u["mean_predicted"]), _pct(c["mean_predicted"]), _pct(c["observed"])]
                   for c, u in zip(last["calibration"], last["calibration_as_learned"], strict=True)])
    out += [("Recalibration narrows the gap in the average and corrects most of the spread: the riskiest tenth is no "
             "longer overstated and the safest no longer understated by half. Predictions still run low, increasingly so "
             "at later landmarks, because risk kept rising during the reporting-lag gap. Ranking running trials is harder "
             "than ranking trials from their start, though the survival model still ranks them better than the yes/no "
             "model."), ""]
    return out


def survival_card(metrics: dict, manifest: dict) -> str:
    """The competing-risks model's report, generated from models/survival/vN/ like the main card."""
    v = f"survival v{manifest['version']}"
    fit = metrics["fit"]
    out = [f"# Survival model card: when and how trials end, {v}", "",
           (f"Generated by `make report` from `models/survival/v{manifest['version']}/`. Trained "
            f"{manifest['trained_at'][:10]} at git `{manifest['git']}` on `{manifest['snowflake_clone']}`, with the "
            f"features of yes/no model v{manifest['yes_no_version']}."), "",
           "## What it predicts", "",
           ("The probability that a trial is terminated within t years of its start, with completion as a competing "
            "event and still-running trials censored at the AACT snapshot. For a running trial: the probability it is "
            "terminated in the next 2 years, given how long it has already run."), "",
           ("Discrete-time competing-risks hazards: one row per 6-month period a trial was at risk (up to 8 years); "
            "LightGBM multiclass (still running / terminated / completed) on the yes/no model's features, the "
            "registration text and the period index. Fit on 2008–2014 starts: "
            f"{fit['n']:,} trials ({fit['terminated']:,} terminated, {fit['completed']:,} completed, "
            f"{fit['censored']:,} still running); {fit['dropped_no_end_date']:,} finished trials without a completion "
            "date are left out."), "",
           "## Ranking by time: time-dependent AUC", "",
           ("Cases: terminated by t. Controls: still running at t or completed by t. Weighted by the inverse "
            "probability of censoring (IPCW), so still-running trials are handled without bias. The yes/no model's "
            "score is ranked the same way on the same trials."), ""]
    rows = []
    for name, c in metrics["cohorts"].items():
        for hz, m in c["by_horizon"].items():
            rows.append([COHORT_NAMES.get(name, name), hz, f"{m['time_auc']:.3f}", f"{m['time_auc_yes_no_model']:.3f}",
                         f"{m['brier']:.4f}", f"{m['brier_null']:.4f}"])
    out += _table(["Cohort", "By", "Survival time-AUC", "Yes/no model", "Brier", "Brier, no-information"], rows)
    for name, c in metrics["cohorts"].items():
        b = c["time_auc_2y_bootstrap"]
        out += [(f"{COHORT_NAMES.get(name, name)} ({c['n']:,} trials, {c['censored']:,} still running): 2-year "
                 f"time-AUC 95% CI {b['ci95'][0]:.3f}–{b['ci95'][1]:.3f}; gain over the yes/no model "
                 f"{b['difference_ci95'][0]:+.3f} to {b['difference_ci95'][1]:+.3f} (paired bootstrap)."), ""]
    out += ["## Calibration", "",
            "Predicted vs observed (Aalen–Johansen) probability of termination by the horizon:", ""]
    out += _table(["Cohort", "By", "Predicted", "Observed"],
                  [[COHORT_NAMES.get(n, n), hz, _pct(m["mean_predicted_cif"]), _pct(m["observed_cif"])]
                   for n, c in metrics["cohorts"].items() for hz, m in c["by_horizon"].items()])
    recal = metrics.get("recalibration")
    out += [("These are the hazards as learned from 2008–2014 starts. They understate termination for later starts, "
             "because the risk itself rose (below)" + (": the served model is recalibrated for that (next section)."
                                                       if recal else "; read them as a lower bound for trials running now.")), ""]
    if recal:
        out += _recalibration(recal)
    stab = metrics.get("refit_stability")
    if stab:
        out += ["## Stability across refits", "",
                (f"The hazards come from an ensemble of {stab['seeds']} fits differing only in the random seed. To "
                 "check it, the model was refit independently (other seeds, rows shuffled, text refit), and both "
                 f"fits gave the next-2-year risk (as learned) of the {stab['running_trials']:,} trials running at "
                 "the snapshot, ranked among themselves:"), ""]
        out += _stability_table(stab)
    out += ["## Termination risk by start cohort", "",
            "Censoring-adjusted (Aalen–Johansen) probability of termination, no model involved:", ""]
    out += _table(["Start years", "Trials", "Still running", "Within 1 year", "Within 2 years", "Within 5 years"],
                  [[r["start_years"], f"{r['n']:,}", _pct(r["still_running"]), _pct(r["terminated_1y"]),
                    _pct(r["terminated_2y"]), _pct(r["terminated_5y"])] for r in metrics.get("incidence_by_start_cohort", [])])
    return "\n".join(out)


if __name__ == "__main__":
    import sys

    from ctrisk.ml.registry import MODELS_DIR, latest

    version = int(sys.argv[1]) if len(sys.argv) > 1 else latest(MODELS_DIR)
    folder = MODELS_DIR / f"v{version}"
    docs = {n: json.loads((folder / f"{n}.json").read_text()) for n in ("metrics", "manifest", "features")}
    audit_path = folder / "audit_point_in_time.json"
    audit = json.loads(audit_path.read_text()) if audit_path.exists() else None
    out = MODELS_DIR.parent / "docs" / "model_card.md"
    out.write_text(card(docs["metrics"], docs["manifest"], docs["features"], audit, _latest_backtest(MODELS_DIR)))
    print(f"wrote {out.relative_to(MODELS_DIR.parent)} for v{version}")
    survival = MODELS_DIR / "survival"
    if any(survival.glob("v*")):
        sv = latest(survival)
        sdocs = {n: json.loads((survival / f"v{sv}" / f"{n}.json").read_text()) for n in ("metrics", "manifest")}
        sout = MODELS_DIR.parent / "docs" / "survival_card.md"
        sout.write_text(survival_card(sdocs["metrics"], sdocs["manifest"]))
        print(f"wrote {sout.relative_to(MODELS_DIR.parent)} for survival v{sv}")
