"""Model card: one auditable report for a model version, generated from the files that version saved.

Every number comes from models/v{N}/ (metrics.json, manifest.json, features.json, and the point-in-time
audit and backtest results when they exist). Nothing is typed by hand, so the card cannot drift from the
model. Numbers a version did not compute are marked as pending rather than left out. The structure follows
the items TRIPOD+AI asks a prediction-model report to state: outcome, population, predictors and when they
were measured, sample sizes, missing data, model building, validation, performance, and limitations.
"""
import json
from pathlib import Path

from ctrisk.ml.features import CATEGORICAL, EDIT_PRONE, FAERS

PENDING = "pending (next `make train`)"
COHORT_LAST_ARCHIVE = "2020-12-01"     # the audit covers 2017-2020 starts; earlier last archives leave it partial
POINT_IN_TIME = set(FAERS) | {"sponsor_prior_trials", "sponsor_prior_termination_rate", "sponsor_trials_started_2y"}
ABLATION_TEXT = {
    "lightgbm_no_text": "without registration text",
    "lightgbm_no_burden": "without burden & eligibility fields",
    "lightgbm_no_faers": "without FAERS reporting history",
    "lightgbm_stable_only": "without any edit-prone field or text (floor under post-start edits)",
}


def _f(v, d=3) -> str:
    return PENDING if v is None else f"{v:.{d}f}"


def _pct(v, d=1) -> str:
    return PENDING if v is None else f"{v * 100:.{d}f}%"


def _events(split: dict) -> str:
    return f"{round(split['n'] * split['base_rate']):,} ({_pct(split['base_rate'])})"


def _timing(column: str) -> str:
    if column in POINT_IN_TIME:
        return "as of the start date"
    if column in EDIT_PRONE:
        return "latest record; often edited after start"
    return "latest record"


def _table(header: list[str], rows: list[list]) -> list[str]:
    return ["| " + " | ".join(header) + " |", "|" + "---|" * len(header),
            *["| " + " | ".join(str(c) for c in r) + " |" for r in rows], ""]


def _fit(test: dict) -> str:
    fit = test.get("calibration_fit")
    return PENDING if not fit else f"intercept {fit['intercept']:.2f} (0 is ideal), slope {fit['slope']:.2f} (1 is ideal)"


def card(metrics: dict, manifest: dict, features: dict, audit: dict | None = None, backtest: dict | None = None) -> str:
    t = metrics["targets"]["label"]
    lg, base = t["models"]["lightgbm"], t["models"]["logistic_regression"]
    test, sp = lg["test"], t["splits"]
    v = f"v{manifest['version']}"
    out = [f"# Model card: trial termination risk, {v}", "",
           (f"Generated by `make report` from `models/{v}/`. Trained {manifest['trained_at'][:10]} at git "
           f"`{manifest['git']}` on the Snowflake snapshot `{manifest['snowflake_clone']}`."), "",
           "## Status", "",
           ("**Preliminary.** Registry features come from the latest version of each ClinicalTrials.gov record, "
            "not the version at the trial's start, so the held-out numbers below may be inflated by edits made "
            "after trials started. "
            + ("The point-in-time audit below measures this." if audit else
               "The point-in-time audit (`make audit-build audit`) has not been run for this version.")
            + " AUC measures ranking. Risk percentages are calibrated on 2015–2016 starts only. "
              "Per-trial contributors describe the model, not causes of termination."), "",
           "## What it predicts", "",
           "- **Outcome:** a registered trial ends as `TERMINATED` (1) rather than `COMPLETED` (0).",
           ("- **Population:** interventional Phase 1–3 drug or biologic trials on ClinicalTrials.gov (AACT). "
           "Withdrawn, suspended, unknown-status and still-running trials carry no label and are excluded from "
           "training and evaluation."),
           "- **Scored:** trials currently not yet recruiting, recruiting, active, or enrolling by invitation.",
           ("- **Intended use:** ranking active trials for review. Not intended as a probability for an individual "
           "trial's decision-making, and not a causal account of why trials stop."), "",
           "## Predictors and when they were measured", ""]
    cols = features["columns"]
    out += _table(["Predictor", "Type", "Measured"],
                  [[f"`{c}`", "categorical" if c in CATEGORICAL else "numeric / flag", _timing(c)] for c in cols]
                  + [["registration text", f"TF-IDF 1–2grams → SVD, {features.get('text_components', 0)} components",
                      "latest record; often edited after start"]])
    out += [(f"{sum(c in POINT_IN_TIME for c in cols)} of {len(cols)} tabular predictors are measured as of the "
            "start date (FAERS reports received before the start month; sponsor trials that ended or started "
            "before the start date). The rest come from the latest registry record. Missing values: LightGBM's "
            "native handling; median imputation plus missing indicators for the logistic baseline; unseen "
            "categories at scoring map to missing."), "",
            "## Samples", ""]
    out += _table(["Split", "Start years", "Trials", "Terminated", "Role"], [
        ["train", "2008–2014", f"{sp['train']['n']:,}", _events(sp["train"]),
         "fit; hyperparameters tuned on <2013 vs 2013–2014"],
        ["test", "2015–2016", f"{sp['test']['n']:,}", _events(sp["test"]),
         "headline metrics; never used for tuning or text fitting"],
        ["recent", "2017–2020", f"{sp['recent']['n']:,}", _events(sp["recent"]),
         "secondary; still censored, over-represents early terminations"]])
    grid = t.get("grid", [])
    params = t["params"]
    out += ["Event counts are n × base rate from the saved metrics, rounded."
            if "positives" not in test else f"Test terminations counted directly: {test['positives']:,}.", "",
            "## Model", "",
            (f"LightGBM, {params['n_estimators']} trees, {params['num_leaves']} leaves, learning rate "
            f"{params['learning_rate']}, min {params['min_child_samples']} trials per leaf; chosen from a "
            f"{len(grid)}-point grid by AUC on the inner 2013–2014 split with early stopping. Baseline: "
            "logistic regression on the same tabular inputs without text."), "",
            "## Performance on 2015–2016 starts (held out)", ""]
    ci = test.get("roc_auc_ci95") or [None, None]
    out += _table(["Metric", "LightGBM", "Logistic baseline"], [
        ["ROC AUC (95% bootstrap CI)", f"{test['roc_auc']:.3f} ({_f(ci[0])}–{_f(ci[1])})", f"{base['test']['roc_auc']:.3f}"],
        ["PR AUC", f"{test['pr_auc']:.3f}", f"{base['test']['pr_auc']:.3f}"],
        ["Termination rate in the riskiest tenth", _pct(test["precision_top_10pct"]), _pct(base["test"]["precision_top_10pct"])],
        ["Base rate", _pct(test["base_rate"]), ""],
        ["Brier score", f"{test['brier']:.4f}", f"{base['test']['brier']:.4f}"],
        ["Calibration", _fit(test), ""]])
    if test.get("calibration"):
        out += ["Calibration by tenth of predicted risk:", ""]
        out += _table(["Tenth", "Mean predicted", "Observed", "Trials"],
                      [[r["bin"] + 1, _pct(r["mean_predicted"]), _pct(r["observed"]), f"{r['n']:,}"]
                       for r in test["calibration"]])
    out += ["## Robustness", "", "Test AUC when the model is retrained without a feature group:", ""]
    out += _table(["Model", "Test AUC", "Change"],
                  [["full model", f"{test['roc_auc']:.3f}", ""]]
                  + [[ABLATION_TEXT[k], f"{t['models'][k]['test']['roc_auc']:.3f}",
                      f"{t['models'][k]['test']['roc_auc'] - test['roc_auc']:+.3f}"] if k in t["models"]
                     else [ABLATION_TEXT[k], PENDING, ""] for k in ABLATION_TEXT])
    folds = t.get("rolling_origin")
    out += [("Rolling origin: fit on training starts before each window, test on the two-year window. "
            "Parameters were tuned on 2013–2014, so the earlier windows are slightly optimistic."), ""]
    out += (_table(["Test starts", "Trained on", "Trials", "Terminated", "AUC", "Calibration"],
                   [[f["test_years"], f"{f['train_n']:,}", f"{f['n']:,}", f"{f['positives']:,}", f"{f['roc_auc']:.3f}",
                     _fit(f)] for f in folds]) if folds else [PENDING, ""])
    out += [f"Recent starts (2017–2020, censored): AUC {lg['recent']['roc_auc']:.3f} on {lg['recent']['n']:,} trials.", ""]
    for key, title in (("by_sponsor_class", "sponsor class"), ("by_phase", "phase"), ("by_start_year", "start year")):
        groups = t.get(key)
        out += [f"Test AUC by {title}:", ""]
        out += (_table(["Group", "Trials", "Terminated", "AUC"],
                       [[g, f"{r['n']:,}", f"{r['positives']:,}" if "positives" in r else "", f"{r['roc_auc']:.3f}"]
                        for g, r in groups.items()]) if groups else [PENDING, ""])
    out += ["## Point-in-time audit (2017–2020 starts)", ""]
    if audit:
        m, s = audit["matched"], audit["strict"]
        archives = audit.get("archives") or []
        line = f"{audit['n_matched']:,} of {audit['n_cohort']:,} trials had an archived record"
        if archives:
            line += f", drawn from {len(archives)} monthly AACT archives, {archives[0]} to {archives[-1]}"
        out += [line + ".", ""]
        if archives and archives[-1] < COHORT_LAST_ARCHIVE:
            out += [(f"**Partial: archives cover only part of 2017–2020.** Trials that started after {archives[-1]} "
                     "are matched to an older record or not at all; the decision waits for the full set."), ""]
        areas = audit.get("areas_from_latest") or {}
        if areas:
            share = max(areas.values())
            out += [("Archives without MeSH ancestors cannot say a trial's top-level disease area; "
                     f"disease areas kept from the latest record for {_pct(share)} of trials."), ""]
        out += _table(["Trials", "n", "Latest-record AUC", "Point-in-time AUC", "Drop (95% CI)"],
                      [[name, f"{r['n']:,}", f"{r['latest']['roc_auc']:.3f}", f"{r['point_in_time']['roc_auc']:.3f}",
                        f"{r['auc_drop']:+.3f} ({r['auc_drop_ci95'][0]:+.3f} to {r['auc_drop_ci95'][1]:+.3f})"]
                       for name, r in (("with an archived record", m), ("record predates start", s))])
        top = list(audit["change_rates"].items())[:8]
        out += ["Fields whose values changed most unevenly between start and now (terminated minus completed):", ""]
        out += _table(["Field", "Changed, terminated", "Changed, completed", "AUC drop if only this is point-in-time"],
                      [[f"`{c}`", _pct(r["terminated"]), _pct(r["completed"]),
                        f"{audit['swap_one_column'].get(c, 0):+.3f}"] for c, r in top])
        if audit.get("unseen_levels"):
            out += [f"Archived categories the model never saw (format drift, or a record edited from outside the modelled population, e.g. phase N/A to Phase 2): {audit['unseen_levels']}", ""]
    else:
        out += ["Not run for this version. See `docs/plans/2026-09-29-m6-honest-model.md`, Task 7.", ""]
    out += ["## Prospective backtest", ""]
    runs = (backtest or {}).get("by_version", {})
    scored = {k: r for k, r in runs.items() if "roc_auc" in r}
    if scored:
        out += [f"Run {backtest['run_at'][:10]}: scores written by each version, against outcomes known then.", ""]
        out += _table(["Version", "First scored", "Resolved trials", "Terminated", "AUC (95% CI)", "Calibration"],
                      [[k, r["first_scored"], f"{r['n']:,}", f"{r['positives']:,}",
                        f"{r['roc_auc']:.3f} ({r['roc_auc_ci95'][0]:.3f}–{r['roc_auc_ci95'][1]:.3f})", _fit(r)]
                       for k, r in scored.items()])
        out += ["Resolved trials over-represent early terminations until most scored trials have finished.", ""]
    else:
        out += [("No scored trial has resolved with both outcomes yet. `make backtest` compares scores written "
                 "earlier with outcomes known now; re-run yearly."), ""]
    out += ["## Other targets", ""]
    rows = []
    for key in ("label_enrollment", "label_safety"):
        o = metrics["targets"].get(key)
        if o:
            ot = o["models"]["lightgbm"]["test"]
            oci = ot.get("roc_auc_ci95") or [None, None]
            rows.append([o["description"], f"{o['splits']['test']['n']:,}", _events(o["splits"]["test"]),
                         f"{ot['roc_auc']:.3f} ({_f(oci[0])}–{_f(oci[1])})",
                         f"{o['models']['logistic_regression']['test']['roc_auc']:.3f}"])
    out += _table(["Target", "Test trials", "Positives", "AUC (95% CI)", "Baseline"], rows)
    out += [("Reason-specific targets compare trials terminated for that reason with completed trials; trials "
            "terminated for other reasons are left out. Reasons come from free text (safety labels ≈70–80% precise)."), "",
            "## Limitations", "",
            "- Registry features describe the latest record, not the record at start (see Status).",
            "- Planned enrollment and site counts are excluded because the current record reflects the outcome.",
            ("- FAERS features are a historical reporting signal: FAERS has duplicate and incomplete reports and "
            "cannot establish causation or incidence. They were built from a quarterly sample (Q1 of each year)."),
            ("- The test period is one two-year window of one registry; performance on other periods or registries "
            "is untested except for the rolling-origin windows above."),
            "- Contributors are SHAP values of this model: associations, not mechanisms.", ""]
    return "\n".join(out)


def _latest_backtest(models_dir: Path) -> dict | None:
    runs = sorted(models_dir.glob("backtest_*.json"))
    return json.loads(runs[-1].read_text()) if runs else None


if __name__ == "__main__":
    import sys

    from ctrisk.ml.registry import MODELS_DIR, latest

    version = int(sys.argv[1]) if len(sys.argv) > 1 else latest(MODELS_DIR)
    folder = MODELS_DIR / f"v{version}"
    docs = {n: json.loads((folder / f"{n}.json").read_text()) for n in ("metrics", "manifest", "features")}
    audit_path = folder / "audit_point_in_time.json"
    audit = json.loads(audit_path.read_text()) if audit_path.exists() else None
    out = MODELS_DIR.parent / "docs" / "model_card.md"
    out.write_text(card(docs["metrics"], docs["manifest"], docs["features"], audit, _latest_backtest(MODELS_DIR)))
    print(f"wrote {out.relative_to(MODELS_DIR.parent)} for v{version}")
