-- One-time setup. Run in Snowsight as ACCOUNTADMIN, top to bottom.
-- Replace clinical-trial-risk-frankfu with your bucket name if different.

USE ROLE ACCOUNTADMIN;
CREATE STORAGE INTEGRATION IF NOT EXISTS CTRISK_GCS
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = 'GCS'
    ENABLED = TRUE
    STORAGE_ALLOWED_LOCATIONS = ('gcs://clinical-trial-risk-frankfu/parquet/');
GRANT USAGE ON INTEGRATION CTRISK_GCS TO ROLE SYSADMIN;
SET me = CURRENT_USER();
GRANT ROLE SYSADMIN TO USER IDENTIFIER($me);   -- the pipeline connects as SYSADMIN
-- (if your user name is lowercase or an email, use GRANT ROLE SYSADMIN TO USER "<name>" instead)
-- Copy STORAGE_GCP_SERVICE_ACCOUNT from this output for the bucket permission step:
DESC STORAGE INTEGRATION CTRISK_GCS;

-- Everything the pipeline owns belongs to SYSADMIN, not ACCOUNTADMIN.
USE ROLE SYSADMIN;
CREATE WAREHOUSE IF NOT EXISTS CTRISK_WH
    WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE DATABASE IF NOT EXISTS CTRISK;
CREATE SCHEMA IF NOT EXISTS CTRISK.PIPELINE;
CREATE FILE FORMAT IF NOT EXISTS CTRISK.PIPELINE.PARQUET_FF TYPE = PARQUET;
CREATE STAGE IF NOT EXISTS CTRISK.PIPELINE.PARQUET_STAGE
    URL = 'gcs://clinical-trial-risk-frankfu/parquet/'
    STORAGE_INTEGRATION = CTRISK_GCS
    FILE_FORMAT = CTRISK.PIPELINE.PARQUET_FF;
