-- Load each Parquet folder from the GCS stage. Tables were just recreated, so every file loads.
COPY INTO RAW_TRIALS FROM @PARQUET_STAGE/trials/
    PATTERN = '.*[.]parquet' MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
COPY INTO RAW_TRIAL_ATTRIBUTES FROM @PARQUET_STAGE/trial_attributes/
    PATTERN = '.*[.]parquet' MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
COPY INTO RAW_SPONSOR_OUTCOMES FROM @PARQUET_STAGE/sponsor_outcomes/
    PATTERN = '.*[.]parquet' MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
COPY INTO RAW_TRIAL_DRUG_MAP FROM @PARQUET_STAGE/trial_drug_map/
    PATTERN = '.*[.]parquet' MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
COPY INTO RAW_FAERS_DRUG_EVENTS FROM @PARQUET_STAGE/faers_drug_events/
    PATTERN = '.*[.]parquet' MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
